name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build

      - name: Run lint
        run: npm run lint

#      - name: Run migrations
#        run: npm run typeorm:test schema:sync
#        env:
#          DATABASE_NAME: ests-test
#          DATABASE_HOST: ${{ secrets.REMOTE_HOST }}
#          DATABASE_USERNAME: ${{ secrets.DB_USER }}
#          DATABASE_PASSWORD: ${{ secrets.DB_PASS }}
#          DATABASE_PORT: 5432
#
#      - name: Run tests
#        run: npm run test
#        env:
#          DATABASE_NAME: ests-test
#          DATABASE_HOST: ${{ secrets.REMOTE_HOST }}
#          DATABASE_USERNAME: ${{ secrets.DB_USER }}
#          DATABASE_PASSWORD: ${{ secrets.DB_PASS }}
#          DATABASE_PORT: 5432
#          TCP_PORT: 6060
