name: Node.js CI

#on:
#  push:
#    branches:
#      - dev

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build

      - name: store-env
        uses: GarryOne/store-env@master
        env:
          TCP_PORT: 6060
          DATABASE_NAME: ests
          DATABASE_HOST: localhost
          DATABASE_USERNAME: ${{ secrets.DB_USER }}
          DATABASE_PASSWORD: ${{ secrets.DB_PASS }}
          DATABASE_PORT: 5432

      - name: Copy build to Server
        uses: GarryOne/ssh-deploy@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /var/www/pax/ests-iot-server

      - name: Run migration & start the app
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/pax/ests-iot-server
            npm run typeorm schema:sync
            npm run typeorm migration:run
            pm2 startOrReload dev.ecosystem.config.js --update-env --time
